# Generated by Django 3.2.4 on 2021-07-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_date_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='film',
        ),
    ]
