# Generated by Django 3.2.4 on 2021-07-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_ticket_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='hall',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
