# Generated by Django 3.2.4 on 2021-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_hall_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='place',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
